import esbuild from "esbuild";
import { deflateSync } from "fflate";
import { readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { dirname, join } from "node:path";
import process from "node:process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// The WASM ships inside main.js because Obsidian only downloads main.js,
// manifest.json and styles.css from a release. It is deflated first so that
// main.js stays below the 5 MB that Obsidian Sync's Standard plan accepts
// (5.7 MB raw, 1.9 MB deflated, 2.5 MB as base64). fflate rather than zlib so
// the bytes do not depend on the Node/zlib version, keeping the build
// reproducible; the plugin inflates it with fflate at load.
const wasmSource = join(dirname(import.meta.url.replace("file://", "")), "node_modules/rumdl-wasm/rumdl_lib_bg.wasm");
const wasmDeflated = deflateSync(readFileSync(wasmSource), { level: 9 });
const wasmBase64 = Buffer.from(wasmDeflated).toString("base64");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2020",
  // Obsidian loads main.js as a CommonJS script, where a native import() of a
  // Node builtin does not resolve; lowering it makes esbuild emit require()
  // instead, which the desktop app provides.
  supported: { "dynamic-import": false },
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    // The deflated WASM as a base64 string, inlined at build time.
    "RUMDL_WASM_DEFLATED_BASE64": JSON.stringify(wasmBase64),
  },
});

if (prod) {
  await context.rebuild();
  console.log(`WASM embedded in main.js (${wasmDeflated.length} bytes deflated, ${wasmBase64.length} bytes base64)`);
  process.exit(0);
} else {
  await context.watch();
}
