import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";
import { dirname, join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Read WASM file and convert to base64
const wasmSource = join(dirname(import.meta.url.replace("file://", "")), "node_modules/rumdl-wasm/rumdl_lib_bg.wasm");
const wasmBase64 = readFileSync(wasmSource).toString("base64");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    // Inject WASM as base64 string
    "RUMDL_WASM_BASE64": JSON.stringify(wasmBase64),
  },
});

if (prod) {
  await context.rebuild();
  console.log("WASM embedded in main.js as base64");
  process.exit(0);
} else {
  await context.watch();
}
